FIXTURE_VIDEO_URL = "https://youtu.be/Gr-BGf7rzrY"
VIDEO_OPTIONS = {"start": 10, "end": 20}

FIXTURE_MP4_VIDEO_INFO_JSON = {
    # YoutubeDL metadata JSON
    # id, title, formats, thumbnail, format ...
    "id": "Gr-BGf7rzrY",
    "title": "WOWOW×Vaundy Museum Live on YouTube",
    "fulltitle": "WOWOW×Vaundy Museum Live on YouTube",
    "formats": [
        {
            "format_id": "sb2",
            "format_note": "storyboard",
            "ext": "mhtml",
            "protocol": "mhtml",
            "acodec": "none",
            "vcodec": "none",
            "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L0/default.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLASPO-yJ1mw_7ScbyCsH6O910Pkcw",
            "width": 48,
            "height": 27,
            "fps": 0.03067484662576687,
            "rows": 10,
            "columns": 10,
            "fragments": [
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L0/default.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLASPO-yJ1mw_7ScbyCsH6O910Pkcw",
                    "duration": 3260.0,
                }
            ],
            "resolution": "48x27",
            "aspect_ratio": 1.78,
            "http_headers": {
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36",
                "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
                "Accept-Language": "en-us,en;q=0.5",
                "Sec-Fetch-Mode": "navigate",
            },
            "audio_ext": "none",
            "video_ext": "none",
            "vbr": 0,
            "abr": 0,
            "tbr": None,
            "format": "sb2 - 48x27 (storyboard)",
        },
        {
            "format_id": "sb1",
            "format_note": "storyboard",
            "ext": "mhtml",
            "protocol": "mhtml",
            "acodec": "none",
            "vcodec": "none",
            "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L1/M$M.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLD5ZxLUnsZqfFGHOGvwjr8qCovlNA",
            "width": 80,
            "height": 45,
            "fps": 0.10030674846625767,
            "rows": 10,
            "columns": 10,
            "fragments": [
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L1/M0.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLD5ZxLUnsZqfFGHOGvwjr8qCovlNA",
                    "duration": 996.9418960244649,
                },
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L1/M1.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLD5ZxLUnsZqfFGHOGvwjr8qCovlNA",
                    "duration": 996.9418960244649,
                },
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L1/M2.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLD5ZxLUnsZqfFGHOGvwjr8qCovlNA",
                    "duration": 996.9418960244649,
                },
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L1/M3.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLD5ZxLUnsZqfFGHOGvwjr8qCovlNA",
                    "duration": 269.17431192660524,
                },
            ],
            "resolution": "80x45",
            "aspect_ratio": 1.78,
            "http_headers": {
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36",
                "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
                "Accept-Language": "en-us,en;q=0.5",
                "Sec-Fetch-Mode": "navigate",
            },
            "audio_ext": "none",
            "video_ext": "none",
            "vbr": 0,
            "abr": 0,
            "tbr": None,
            "format": "sb1 - 80x45 (storyboard)",
        },
        {
            "format_id": "sb0",
            "format_note": "storyboard",
            "ext": "mhtml",
            "protocol": "mhtml",
            "acodec": "none",
            "vcodec": "none",
            "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L2/M$M.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLAwsCDTGqYpy0ZO258fFkJnlcjwuw",
            "width": 160,
            "height": 90,
            "fps": 0.10030674846625767,
            "rows": 5,
            "columns": 5,
            "fragments": [
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L2/M0.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLAwsCDTGqYpy0ZO258fFkJnlcjwuw",
                    "duration": 249.23547400611622,
                },
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L2/M1.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLAwsCDTGqYpy0ZO258fFkJnlcjwuw",
                    "duration": 249.23547400611622,
                },
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L2/M2.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLAwsCDTGqYpy0ZO258fFkJnlcjwuw",
                    "duration": 249.23547400611622,
                },
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L2/M3.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLAwsCDTGqYpy0ZO258fFkJnlcjwuw",
                    "duration": 249.23547400611622,
                },
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L2/M4.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLAwsCDTGqYpy0ZO258fFkJnlcjwuw",
                    "duration": 249.23547400611622,
                },
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L2/M5.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLAwsCDTGqYpy0ZO258fFkJnlcjwuw",
                    "duration": 249.23547400611622,
                },
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L2/M6.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLAwsCDTGqYpy0ZO258fFkJnlcjwuw",
                    "duration": 249.23547400611622,
                },
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L2/M7.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLAwsCDTGqYpy0ZO258fFkJnlcjwuw",
                    "duration": 249.23547400611622,
                },
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L2/M8.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLAwsCDTGqYpy0ZO258fFkJnlcjwuw",
                    "duration": 249.23547400611622,
                },
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L2/M9.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLAwsCDTGqYpy0ZO258fFkJnlcjwuw",
                    "duration": 249.23547400611622,
                },
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L2/M10.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLAwsCDTGqYpy0ZO258fFkJnlcjwuw",
                    "duration": 249.23547400611622,
                },
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L2/M11.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLAwsCDTGqYpy0ZO258fFkJnlcjwuw",
                    "duration": 249.23547400611622,
                },
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L2/M12.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLAwsCDTGqYpy0ZO258fFkJnlcjwuw",
                    "duration": 249.23547400611622,
                },
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L2/M13.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLAwsCDTGqYpy0ZO258fFkJnlcjwuw",
                    "duration": 19.938837920489277,
                },
            ],
            "resolution": "160x90",
            "aspect_ratio": 1.78,
            "http_headers": {
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36",
                "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
                "Accept-Language": "en-us,en;q=0.5",
                "Sec-Fetch-Mode": "navigate",
            },
            "audio_ext": "none",
            "video_ext": "none",
            "vbr": 0,
            "abr": 0,
            "tbr": None,
            "format": "sb0 - 160x90 (storyboard)",
        },
        {
            "format_id": "233",
            "format_note": "Default",
            "format_index": None,
            "url": "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1697892196/ei/BHMzZa6DK4Wv2roPusi3-AI/ip/211.212.99.6/id/1abf8119feebceb6/itag/233/source/youtube/requiressl/yes/ratebypass/yes/pfa/1/goi/133/sgoap/clen%3D19879894%3Bdur%3D3260.081%3Bgir%3Dyes%3Bitag%3D139%3Blmt%3D1685477541599941/hls_chunk_host/rr2---sn-n3cgv5qc5oq-nnol.googlevideo.com/mh/8V/mm/31,29/mn/sn-n3cgv5qc5oq-nnol,sn-n3cgv5qc5oq-bh26e/ms/au,rdu/mv/m/mvi/2/pl/25/force_finished/1/initcwndbps/1860000/vprv/1/playlist_type/DVR/dover/13/txp/4532434/mt/1697870225/fvip/2/short_key/1/keepalive/yes/fexp/24007246/beids/24350018/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,goi,sgoap,force_finished,vprv,playlist_type/sig/AGM4YrMwRQIhAOFZKpveu12yDBlehPeQWPfaCaSOdn5JQ0E2c9b8YVPlAiB71RlgYXlvGLqfRXf-YuYqnCQtfoEzAoqKgAbxypoO-A%3D%3D/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/AK1ks_kwRgIhALoipbDD3Xxndu2POTWlTFmBfpaLNEsj8X90gdMuAYToAiEA4qeLdKCg2b7CyTiAIv20EoYVY9VaGdNsXXyEaoDxQf0%3D/playlist/index.m3u8",
            "manifest_url": "https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1697892196/ei/BHMzZa6DK4Wv2roPusi3-AI/ip/211.212.99.6/id/1abf8119feebceb6/source/youtube/requiressl/yes/playback_host/rr2---sn-n3cgv5qc5oq-nnol.googlevideo.com/mh/8V/mm/31%2C29/mn/sn-n3cgv5qc5oq-nnol%2Csn-n3cgv5qc5oq-bh26e/ms/au%2Crdu/mv/m/mvi/2/pl/25/hfr/1/force_finished/1/demuxed/1/tts_caps/1/maudio/1/initcwndbps/1860000/vprv/1/go/1/mt/1697870225/fvip/2/nvgoi/1/short_key/1/ncsapi/1/keepalive/yes/fexp/24007246/beids/24350018/dover/13/itag/0/playlist_type/DVR/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cforce_finished%2Cdemuxed%2Ctts_caps%2Cmaudio%2Cvprv%2Cgo%2Citag%2Cplaylist_type/sig/AGM4YrMwRQIgTo6scJYmLwKntFqTl5HxneXkzHdNaNe9Fsxn5ZQ6NikCIQDsyetOYdHksRORmQzOpXZyha1fN_ydEcXQaxNK3HK1Ww%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AK1ks_kwRQIgbI9NEOc7WyuX1I1BKSGigW3e97E9JO92_kLWtk4j2yMCIQCUwBwQPs9yrba119ad9dWCd_dSn7-RV8EusuWIJZG9fw%3D%3D/file/index.m3u8",
            "language": "en",
            "ext": "mp4",
            "protocol": "m3u8_native",
            "preference": None,
            "quality": -1,
            "has_drm": False,
            "vcodec": "none",
            "source_preference": -1,
            "resolution": "audio only",
            "aspect_ratio": None,
            "http_headers": {
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36",
                "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
                "Accept-Language": "en-us,en;q=0.5",
                "Sec-Fetch-Mode": "navigate",
            },
            "audio_ext": "mp4",
            "video_ext": "none",
            "vbr": 0,
            "abr": None,
            "tbr": None,
            "format": "233 - audio only (Default)",
        },
        {
            "format_id": "234",
            "format_note": "Default",
            "format_index": None,
            "url": "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1697892196/ei/BHMzZa6DK4Wv2roPusi3-AI/ip/211.212.99.6/id/1abf8119feebceb6/itag/234/source/youtube/requiressl/yes/ratebypass/yes/pfa/1/goi/133/sgoap/clen%3D52760375%3Bdur%3D3260.011%3Bgir%3Dyes%3Bitag%3D140%3Blmt%3D1685477547754273/hls_chunk_host/rr2---sn-n3cgv5qc5oq-nnol.googlevideo.com/mh/8V/mm/31,29/mn/sn-n3cgv5qc5oq-nnol,sn-n3cgv5qc5oq-bh26e/ms/au,rdu/mv/m/mvi/2/pl/25/force_finished/1/initcwndbps/1860000/vprv/1/playlist_type/DVR/dover/13/txp/4532434/mt/1697870225/fvip/2/short_key/1/keepalive/yes/fexp/24007246/beids/24350018/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,goi,sgoap,force_finished,vprv,playlist_type/sig/AGM4YrMwRQIhALzQV-WUiC1J3Xs1Jay94TOZu1GYH9Z-P76Ja_PFsVLpAiAGdlE3Zx28OBqHce7EF-s4Q-w50EFvtanJZHmKbRU2LA%3D%3D/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/AK1ks_kwRAIgF86XjEPCMQmPUvB7pREOi9uEYM2c2aWRJuVgk8z5q5kCIAz2p9DnJeLOLUUICfRGCGn952vJRIu2H0vHpbn68jm6/playlist/index.m3u8",
            "manifest_url": "https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1697892196/ei/BHMzZa6DK4Wv2roPusi3-AI/ip/211.212.99.6/id/1abf8119feebceb6/source/youtube/requiressl/yes/playback_host/rr2---sn-n3cgv5qc5oq-nnol.googlevideo.com/mh/8V/mm/31%2C29/mn/sn-n3cgv5qc5oq-nnol%2Csn-n3cgv5qc5oq-bh26e/ms/au%2Crdu/mv/m/mvi/2/pl/25/hfr/1/force_finished/1/demuxed/1/tts_caps/1/maudio/1/initcwndbps/1860000/vprv/1/go/1/mt/1697870225/fvip/2/nvgoi/1/short_key/1/ncsapi/1/keepalive/yes/fexp/24007246/beids/24350018/dover/13/itag/0/playlist_type/DVR/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cforce_finished%2Cdemuxed%2Ctts_caps%2Cmaudio%2Cvprv%2Cgo%2Citag%2Cplaylist_type/sig/AGM4YrMwRQIgTo6scJYmLwKntFqTl5HxneXkzHdNaNe9Fsxn5ZQ6NikCIQDsyetOYdHksRORmQzOpXZyha1fN_ydEcXQaxNK3HK1Ww%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AK1ks_kwRQIgbI9NEOc7WyuX1I1BKSGigW3e97E9JO92_kLWtk4j2yMCIQCUwBwQPs9yrba119ad9dWCd_dSn7-RV8EusuWIJZG9fw%3D%3D/file/index.m3u8",
            "language": "en",
            "ext": "mp4",
            "protocol": "m3u8_native",
            "preference": None,
            "quality": -1,
            "has_drm": False,
            "vcodec": "none",
            "source_preference": -1,
            "resolution": "audio only",
            "aspect_ratio": None,
            "http_headers": {
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36",
                "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
                "Accept-Language": "en-us,en;q=0.5",
                "Sec-Fetch-Mode": "navigate",
            },
            "audio_ext": "mp4",
            "video_ext": "none",
            "vbr": 0,
            "abr": None,
            "tbr": None,
            "format": "234 - audio only (Default)",
        },
    ],
    "thumbnail": "https://i.ytimg.com/vi_webp/Gr-BGf7rzrY/maxresdefault.webp",
    "format": "616 - 1920x1080 (Premium)+251 - audio only (medium)",
    # ...
}

FIXTURE_NON_MP4_VIDEO_INFO_JSON = {
    # YoutubeDL metadata JSON
    # id, title, formats, thumbnail, format ...
    "id": "Gr-BGf7rzrY",
    "title": "WOWOW×Vaundy Museum Live on YouTube",
    "fulltitle": "WOWOW×Vaundy Museum Live on YouTube",
    "formats": [
        {
            "format_id": "sb2",
            "format_note": "storyboard",
            "ext": "mhtml",
            "protocol": "mhtml",
            "acodec": "none",
            "vcodec": "none",
            "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L0/default.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLASPO-yJ1mw_7ScbyCsH6O910Pkcw",
            "width": 48,
            "height": 27,
            "fps": 0.03067484662576687,
            "rows": 10,
            "columns": 10,
            "fragments": [
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L0/default.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLASPO-yJ1mw_7ScbyCsH6O910Pkcw",
                    "duration": 3260.0,
                }
            ],
            "resolution": "48x27",
            "aspect_ratio": 1.78,
            "http_headers": {
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36",
                "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
                "Accept-Language": "en-us,en;q=0.5",
                "Sec-Fetch-Mode": "navigate",
            },
            "audio_ext": "none",
            "video_ext": "none",
            "vbr": 0,
            "abr": 0,
            "tbr": None,
            "format": "sb2 - 48x27 (storyboard)",
        },
        {
            "format_id": "sb1",
            "format_note": "storyboard",
            "ext": "mhtml",
            "protocol": "mhtml",
            "acodec": "none",
            "vcodec": "none",
            "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L1/M$M.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLD5ZxLUnsZqfFGHOGvwjr8qCovlNA",
            "width": 80,
            "height": 45,
            "fps": 0.10030674846625767,
            "rows": 10,
            "columns": 10,
            "fragments": [
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L1/M0.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLD5ZxLUnsZqfFGHOGvwjr8qCovlNA",
                    "duration": 996.9418960244649,
                },
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L1/M1.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLD5ZxLUnsZqfFGHOGvwjr8qCovlNA",
                    "duration": 996.9418960244649,
                },
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L1/M2.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLD5ZxLUnsZqfFGHOGvwjr8qCovlNA",
                    "duration": 996.9418960244649,
                },
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L1/M3.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLD5ZxLUnsZqfFGHOGvwjr8qCovlNA",
                    "duration": 269.17431192660524,
                },
            ],
            "resolution": "80x45",
            "aspect_ratio": 1.78,
            "http_headers": {
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36",
                "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
                "Accept-Language": "en-us,en;q=0.5",
                "Sec-Fetch-Mode": "navigate",
            },
            "audio_ext": "none",
            "video_ext": "none",
            "vbr": 0,
            "abr": 0,
            "tbr": None,
            "format": "sb1 - 80x45 (storyboard)",
        },
        {
            "format_id": "sb0",
            "format_note": "storyboard",
            "ext": "mhtml",
            "protocol": "mhtml",
            "acodec": "none",
            "vcodec": "none",
            "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L2/M$M.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLAwsCDTGqYpy0ZO258fFkJnlcjwuw",
            "width": 160,
            "height": 90,
            "fps": 0.10030674846625767,
            "rows": 5,
            "columns": 5,
            "fragments": [
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L2/M0.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLAwsCDTGqYpy0ZO258fFkJnlcjwuw",
                    "duration": 249.23547400611622,
                },
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L2/M1.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLAwsCDTGqYpy0ZO258fFkJnlcjwuw",
                    "duration": 249.23547400611622,
                },
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L2/M2.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLAwsCDTGqYpy0ZO258fFkJnlcjwuw",
                    "duration": 249.23547400611622,
                },
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L2/M3.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLAwsCDTGqYpy0ZO258fFkJnlcjwuw",
                    "duration": 249.23547400611622,
                },
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L2/M4.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLAwsCDTGqYpy0ZO258fFkJnlcjwuw",
                    "duration": 249.23547400611622,
                },
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L2/M5.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLAwsCDTGqYpy0ZO258fFkJnlcjwuw",
                    "duration": 249.23547400611622,
                },
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L2/M6.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLAwsCDTGqYpy0ZO258fFkJnlcjwuw",
                    "duration": 249.23547400611622,
                },
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L2/M7.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLAwsCDTGqYpy0ZO258fFkJnlcjwuw",
                    "duration": 249.23547400611622,
                },
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L2/M8.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLAwsCDTGqYpy0ZO258fFkJnlcjwuw",
                    "duration": 249.23547400611622,
                },
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L2/M9.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLAwsCDTGqYpy0ZO258fFkJnlcjwuw",
                    "duration": 249.23547400611622,
                },
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L2/M10.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLAwsCDTGqYpy0ZO258fFkJnlcjwuw",
                    "duration": 249.23547400611622,
                },
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L2/M11.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLAwsCDTGqYpy0ZO258fFkJnlcjwuw",
                    "duration": 249.23547400611622,
                },
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L2/M12.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLAwsCDTGqYpy0ZO258fFkJnlcjwuw",
                    "duration": 249.23547400611622,
                },
                {
                    "url": "https://i.ytimg.com/sb/Gr-BGf7rzrY/storyboard3_L2/M13.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiMwsGjBg==&sigh=rs$AOn4CLAwsCDTGqYpy0ZO258fFkJnlcjwuw",
                    "duration": 19.938837920489277,
                },
            ],
            "resolution": "160x90",
            "aspect_ratio": 1.78,
            "http_headers": {
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36",
                "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
                "Accept-Language": "en-us,en;q=0.5",
                "Sec-Fetch-Mode": "navigate",
            },
            "audio_ext": "none",
            "video_ext": "none",
            "vbr": 0,
            "abr": 0,
            "tbr": None,
            "format": "sb0 - 160x90 (storyboard)",
        },
    ],
    "thumbnail": "https://i.ytimg.com/vi_webp/Gr-BGf7rzrY/maxresdefault.webp",
    "format": "616 - 1920x1080 (Premium)+251 - audio only (medium)",
    # ...
}
